### ISSUE TITLE
Peer code review

### ISSUE THREAD

**Issue by jcmann** [kmracchini/stitchable#3]
# Design/Code Review 1

### Reviewer: Jen M

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person|Your problem statement is very well-worded, professional, and concise. I think it's especially helpful that you compare it to Ravelry and provide that context.|
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | I really like that all your major action items are top-level nav items. Your forms do all make sense and are very simple. I know you were looking for other ways to search, and I think being able to search by color would be really helpful. I know that you can browse by designer, but it might be an interesting stretch goal to also search by designer in case the user maybe misses that you can search that way?|
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>|You were SO thorough with this! I really liked that you actually specified this, I think I missed this part of the instructions. You'll definitely have the relationships you'll need, and it seems well balanced. I mentioned this when we talked, but I would definitely consider replacing some of those varchar columns with number columns to make your data processing simpler. |
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverage. |Good call putting one of your properties files in the gitignore, I should do that, it's way safer. I also like that you're going to implement the GenericDao it looks like, I'm hoping to do that for mine, too. I also like that you implemented PropertyLike, that is also going to be super helpful for your searching because of how much I'd guess people would search by names. Overall you were very thorough!! |

**Comment by pawaitemadisoncollege** [comment]
Thanks for the thorough review @jcmann - shows that you dove into the design. I like that you identified some techniques to borrow too!
